name: Pagination Testing
run-name: ${{github.actor}} is testing out the pagination
on: [push]
jobs:
  test-pagination:
  runs-on: $${{ matrix.os }}
  env:
    NODE_ENV: test
    DATABASE_URL: ${{ secrets.DATABASE_URL }}
    S3_REGION: us-west-1
    S3_KEY: ${{ secrets.S3_KEY }}
    S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
    S3_BUCKET_NAME: trpctextappbuck
    # These are okay to share as it only has GetObject Permissions
    CLIENT_S3_KEY: AKIA5NV64QSFLO6N5GVS
    CLIENT_S3_SECRET_KEY: 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
  strategy:
    matrix:
      node: ['18.x']
      os: [ubuntu-latest]
  steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: pnpm/action-setup@v2.2.4
      with:
        version: 7.26.0
    - name: Use Node ${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
    - name: Install deps (with cache)
        run: pnpm install
    - name: Next.js cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-${{ runner.node }}-${{ hashFiles('**/pnpm-lock.yaml') }}-nextjs
    - name: Setup Prisma
        run: pnpm prebuild
    - name: Setup Prisma
        run: pnpm prebuild

    - name: Build and test
      run: pnpm build && pnpm test-start && pnpm test-dev

    - name: Upload test results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: test results
        path: |
          playwright/test-results

